[package]
name = "macroquad-canvas-2d"
version = "0.1.1"
authors = ["nicolas <nicolas.sabbatini.95@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Add canvas functionality to macroquad."
repository = "https://git.sr.ht/~nik_codes/macroquad-canvas"
categories = []

[dependencies]
macroquad = "0.3.0-alpha.17"

[profile.dev.package.'*']
opt-level = 3
